### PR TITLE
[GEOT-5428] Support NetCDF rotated pole projection

### PR DESCRIPTION
**Pull request by bencaradocdavies**
See: https://osgeo-org.atlassian.net/browse/GEOT-5428

This PR depends on https://github.com/geotools/geotools/pull/1205 and is expected to break the build until https://github.com/geotools/geotools/pull/1205 is merged. (The single added method does not yet exist.)

This is the GeoServer counterpart to the GeoTools pull request; it adds a single method call, but also adds test coverage. In addition there is an important bug fix for https://osgeo-org.atlassian.net/browse/GEOS-7571

CF Conventions section for rotated pole projection:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch05s06.html

@simboss or @dromagnoli please review. I will make some line comments to explain a few of the details.

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
As noted above, compilation fails as the new method added by https://github.com/geotools/geotools/pull/1205 is not present:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project gs-netcdf-out: Compilation failure
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/main/java/org/geoserver/wcs/responses/NetCDFCRSWriter.java:[295,20] error: cannot find symbol
```

File: src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFBaseTest.java [hunk 1]
```diff
@@ -1,4 +1,4 @@
-/* (c) 2015 Open Source Geospatial Foundation - all rights reserved
+/* (c) 2015 - 2016 Open Source Geospatial Foundation - all rights reserved
```
Comment (bencaradocdavies) [inline src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFBaseTest.java]: The copyright header policy change has not yet reached GeoServer.

File: src/extension/netcdf-out/src/main/java/org/geoserver/wcs/responses/NetCDFCRSWriter.java [hunk 2]
```diff
@@ -291,7 +291,8 @@ private void setGridMappingVariableAttributes(NetcdfFileWriter writer, Coordinat
             Set<String> keySet = referencingToNetCDFParameters.keySet();
 
             // getting the list of parameters from the GT Referencing Projection 
-            ParameterValueGroup values = conversionFromBase.getParameterValues();
+            ParameterValueGroup values = projection
+                    .getNetcdfParameters(conversionFromBase.getParameterValues());
```
Comment (bencaradocdavies) [inline src/extension/netcdf-out/src/main/java/org/geoserver/wcs/responses/NetCDFCRSWriter.java]: This is the new method implemented in https://github.com/geotools/geotools/pull/1205 to compute NetCDF parameter values from OGC parameter values. This method is required because the rotated pole projection breaks the assumption that parameter mapping is a simple renaming.

File: src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFBaseTest.java [hunk 3]
```diff
@@ -27,6 +27,7 @@ protected void setUpTestData(SystemTestData testData) throws Exception {
             "user_projections/" + netcdfProjectionsDefinition);
         final File projectionFile = new File(projectionFileDir, netcdfProjectionsDefinition);
         System.setProperty(NetCDFCRSAuthorityFactory.SYSTEM_DEFAULT_USER_PROJ_FILE, projectionFile.getCanonicalPath());
+        testData.copyTo(getClass().getResourceAsStream("reduced-cf-standard-name-table.xml"), "cf-standard-name-table.xml");
```
Comment (bencaradocdavies) [inline src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFBaseTest.java]: Setup for this resource pulled up into this superclass to avoid an ugly stack trace in the test output when the table does no exist.

File: src/pom.xml [hunk 4]
```diff
@@ -1266,6 +1266,7 @@
      <include>**/*.tiff</include>
      <include>**/*.zip</include>
      <include>**/*.json</include>
+     <include>**/*.nc</include>
```
Comment (bencaradocdavies) [inline src/pom.xml]: This change would not be necessary if ```gs-netcdf-out```  kept all its test resources in ```test-data``` or ```src/test/resources```.

File: src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java [hunk 5]
```diff
@@ -1282,6 +1282,9 @@ private Filter filter(String startAttribute, String endAttribute, Comparable min
             throw new UnsupportedOperationException("Only structuredGridCoverage2DReaders are currently supported");
         }
         List<DimensionBean> dimensions = new ArrayList<DimensionBean>();
+        if (accessor == null) {
```
Comment (bencaradocdavies) [inline src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java]: This null guard is the fix for https://osgeo-org.atlassian.net/browse/GEOS-7571.

**Comment by dromagnoli** [comment]
@bencaradocdavies  Looks good to me.
+1 on merging it once the other PR is merged.

**Comment by bencaradocdavies** [comment]
Thanks @dromagnoli. Merged and, after the build passed, cherry-picked onto 2.9.x (build also passed).
